In [ ]:
import pandas as pd

dat = pd.read_csv("simulated_data.csv")

# 1. Group by sex
grouped_by_sex = dat.groupby(['sex']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_sex)

# 2. Group by age.binned
grouped_by_age = dat.groupby(['age.binned']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_age)

# 3. Group by knew.celebrity.y.n
grouped_by_celebrity = dat.groupby(['knew.celebrity.y.n']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_celebrity)

# 4. Group by sex and knew.celebrity.y.n
grouped_by_sex_celebrity = dat.groupby(['sex', 'knew.celebrity.y.n']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_sex_celebrity)

# 5. Group by age.binned and knew.celebrity.y.n
grouped_by_age_celebrity = dat.groupby(['age.binned', 'knew.celebrity.y.n']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_age_celebrity)

# 6. Group by sex and age.binned
grouped_by_sex_age = dat.groupby(['sex', 'age.binned']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_sex_age)

# 7. Group by sex, age.binned, and knew.celebrity.y.n
grouped_by_sex_age_celebrity = dat.groupby(['sex', 'age.binned', 'knew.celebrity.y.n']).agg(
    mean_time_to_death=('time.to.death', 'mean'),
    count=('time.to.death', 'size')
).reset_index()
print(grouped_by_sex_age_celebrity)